#!/usr/bin/env ruby

# This script was inspired by one written by Erik Kastner, 
# and a blog describing it's needs and usage can be found at 
# http://metaatem.net/2007/04/20/fun-with-active_record-and-sqlite3
# 
# It can be used for hands on quick and dirty testing to see how the library 
# is working in the IRB console. It will open an IRB console with
# with a Templater::Generator object instantiated: @generator. 
# You can render a template in the console to see what is going on.
#   @user_gen.invoke! 
#
# This file must be executable to work: [sudo] chmod 775 spec/console
#

require 'rubygems'
require 'merb-core'
require 'merb-gen'
require 'templater/spec/helpers'
require 'activerecord'
require 'irb'

Merb.disable(:initfile)

require File.dirname(__FILE__) + '/../lib/generators/rear_views_generator'
require File.dirname(__FILE__) + "/database_setup"
include DatabaseSetup


@user_gen = Merb::Generators::RearViewsGenerator.new( 'spec/tmp', {}, 'User' )
@project_gen = Merb::Generators::RearViewsGenerator.new( 'spec/tmp', {}, 'Project' )
@task_gen = Merb::Generators::RearViewsGenerator.new( 'spec/tmp', {}, 'Task' )


# start the conole with these variables
IRB.start if __FILE__ == $0